meta_product_name: "Track my nutrients"
meta_title: "Track My Nutrients - Your very own nutrition coach "
meta_description: "To make life easier for people who are dieting."
meta_image: "couv.png"                       # should exist in `app/assets/images/`
twitter_account: "@track-my-nutrients"
